services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername       # 👈 change this
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword       # 👈 change this
      - key: N8N_HOST
        value: n8n.onrender.com   # 👈 replace with your Render service URL
      - key: N8N_PORT
        value: "5678"

      # Neon DB connection
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: ep-falling-truth-a118o8q7-pooler.ap-southeast-1.aws.neon.tech
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_USER
        value: neondb_owner
      - key: DB_POSTGRESDB_PASSWORD
        sync: false   # 👈 set this in Render Dashboard manually (safer)
      - key: DB_POSTGRESDB_SSL_CA
        value: "true"
